### ISSUE TITLE
Add twinpeaks project goals to README

### ISSUE THREAD

**Issue by bigdoods** [ArupAus/twinpeaks-frontend#1]
Hi,

Could you extend the README to explain a little about what twinpeaks is used for i.e why it was developed, what it does, how it may be reused, why the 'twinpeaks' name etc. please?

Thanks,

John

**Comment by MichaelMarkieta** [comment]
Hey @bigdoods , this was set up to run a workshop at Arup in San Fransisco. The repo is based on the [Angular Full Stack Generator](https://angular-fullstack.github.io/generator-angular-fullstack/) to bring a bunch of new developers up to speed with NodeJS development using a stack that is widely used in the Americas region. The repo is basically dead now, but I would be happy to discuss any questions you have in regards to the actual code that was modified from the generator for the workshop, or anything else related to full stack web development via email.
